### ISSUE TITLE
Allow assignment of modifiers/samples to subset of samples/regions

### ISSUE THREAD

**Issue by alexander-held** [alexander-held/cabinetry#214]
In version `v0.2.0` it is possible to assign modifiers to a subset of samples via a mandatory `Samples` property. Several things can be improved:
- `Samples` property should be optional and default to all samples -> #218
  -  this is already the case when specifying samples on which smoothing should act in systematic variations

It should be possible to define a sample that only populates a subset of all regions, similarly to how systematics have a `Samples` property to define the samples they act on. This requires the addition of a new optional `Regions` property to samples.

This simplifies setups where samples may only enter in some regions of phase space. Together with the existing possibility to define systematics per sample, it would then also be possible to define systematics per subset of regions (assuming implementation of #213 as well): a sample could be split per region, different systematics could be implemented per subset of samples, and correlated again as needed. This scenario could be simplified further by also introducing a `Regions` property to systematics.

The configuration uses the concepts regions > samples > systematics, with settings at a lower level overriding settings at a higher level. To react at a lower level to a setting from the higher level, the following scenarios should be made available:

- [x] sample with region dependence -> requires `Regions` property for samples, as proposed here -> done in #217
- [X] systematics with sample dependence -> `Samples` property already exists for systematics -> made optional in #218
- [ ] systematics with region dependence -> can be achieved by combining `Samples` property of systematics, splitting samples, and using new `Regions` property for samples proposed here, but can more conveniently be achieved with new `Regions` property for systematics -> #220

**Comment by alexander-held** [comment]
The implementations use an option at the lower level (from high to low: region > sample > systematic) to specify the corresponding higher level objects. For samples with region dependence, that means using a `"Regions"` setting in the sample block. It would also be possible to use the higher level, for example by introducing a `"Samples"` setting for each region.

The current approach seems more suitable for common use cases where the custom handling is only needed for a small subset of samples and systematics. It also avoids having to specify information at the level where it is not yet relevant: a region does not need to know about the samples that enter.
